// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: hypixel/hypixel.proto

package hypixel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SkyBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Profile       string                 `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkyBlockRequest) Reset() {
	*x = SkyBlockRequest{}
	mi := &file_hypixel_hypixel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkyBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkyBlockRequest) ProtoMessage() {}

func (x *SkyBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypixel_hypixel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkyBlockRequest.ProtoReflect.Descriptor instead.
func (*SkyBlockRequest) Descriptor() ([]byte, []int) {
	return file_hypixel_hypixel_proto_rawDescGZIP(), []int{0}
}

func (x *SkyBlockRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SkyBlockRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

type SkyBlockProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Profile       string                 `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkyBlockProfile) Reset() {
	*x = SkyBlockProfile{}
	mi := &file_hypixel_hypixel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkyBlockProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkyBlockProfile) ProtoMessage() {}

func (x *SkyBlockProfile) ProtoReflect() protoreflect.Message {
	mi := &file_hypixel_hypixel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkyBlockProfile.ProtoReflect.Descriptor instead.
func (*SkyBlockProfile) Descriptor() ([]byte, []int) {
	return file_hypixel_hypixel_proto_rawDescGZIP(), []int{1}
}

func (x *SkyBlockProfile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SkyBlockProfile) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SkyBlockProfile) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

type NetworthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         float64                `protobuf:"fixed64,1,opt,name=total,proto3" json:"total,omitempty"`
	Unsoulbound   float64                `protobuf:"fixed64,2,opt,name=unsoulbound,proto3" json:"unsoulbound,omitempty"`
	Profile       *SkyBlockProfile       `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworthResponse) Reset() {
	*x = NetworthResponse{}
	mi := &file_hypixel_hypixel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworthResponse) ProtoMessage() {}

func (x *NetworthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hypixel_hypixel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworthResponse.ProtoReflect.Descriptor instead.
func (*NetworthResponse) Descriptor() ([]byte, []int) {
	return file_hypixel_hypixel_proto_rawDescGZIP(), []int{2}
}

func (x *NetworthResponse) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *NetworthResponse) GetUnsoulbound() float64 {
	if x != nil {
		return x.Unsoulbound
	}
	return 0
}

func (x *NetworthResponse) GetProfile() *SkyBlockProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type DungeonClasses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healer        float64                `protobuf:"fixed64,1,opt,name=healer,proto3" json:"healer,omitempty"`
	Mage          float64                `protobuf:"fixed64,2,opt,name=mage,proto3" json:"mage,omitempty"`
	Tank          float64                `protobuf:"fixed64,3,opt,name=tank,proto3" json:"tank,omitempty"`
	Berserk       float64                `protobuf:"fixed64,4,opt,name=berserk,proto3" json:"berserk,omitempty"`
	Archer        float64                `protobuf:"fixed64,5,opt,name=archer,proto3" json:"archer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DungeonClasses) Reset() {
	*x = DungeonClasses{}
	mi := &file_hypixel_hypixel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DungeonClasses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DungeonClasses) ProtoMessage() {}

func (x *DungeonClasses) ProtoReflect() protoreflect.Message {
	mi := &file_hypixel_hypixel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DungeonClasses.ProtoReflect.Descriptor instead.
func (*DungeonClasses) Descriptor() ([]byte, []int) {
	return file_hypixel_hypixel_proto_rawDescGZIP(), []int{3}
}

func (x *DungeonClasses) GetHealer() float64 {
	if x != nil {
		return x.Healer
	}
	return 0
}

func (x *DungeonClasses) GetMage() float64 {
	if x != nil {
		return x.Mage
	}
	return 0
}

func (x *DungeonClasses) GetTank() float64 {
	if x != nil {
		return x.Tank
	}
	return 0
}

func (x *DungeonClasses) GetBerserk() float64 {
	if x != nil {
		return x.Berserk
	}
	return 0
}

func (x *DungeonClasses) GetArcher() float64 {
	if x != nil {
		return x.Archer
	}
	return 0
}

type DungeonFloorStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Completions   float64                `protobuf:"fixed64,1,opt,name=completions,proto3" json:"completions,omitempty"`
	PersonalBest  float64                `protobuf:"fixed64,2,opt,name=personalBest,proto3" json:"personalBest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DungeonFloorStats) Reset() {
	*x = DungeonFloorStats{}
	mi := &file_hypixel_hypixel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DungeonFloorStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DungeonFloorStats) ProtoMessage() {}

func (x *DungeonFloorStats) ProtoReflect() protoreflect.Message {
	mi := &file_hypixel_hypixel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DungeonFloorStats.ProtoReflect.Descriptor instead.
func (*DungeonFloorStats) Descriptor() ([]byte, []int) {
	return file_hypixel_hypixel_proto_rawDescGZIP(), []int{4}
}

func (x *DungeonFloorStats) GetCompletions() float64 {
	if x != nil {
		return x.Completions
	}
	return 0
}

func (x *DungeonFloorStats) GetPersonalBest() float64 {
	if x != nil {
		return x.PersonalBest
	}
	return 0
}

type DungeonsStatsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ClassAverage       float64                `protobuf:"fixed64,1,opt,name=classAverage,proto3" json:"classAverage,omitempty"`
	CatacombsLevel     float64                `protobuf:"fixed64,2,opt,name=catacombsLevel,proto3" json:"catacombsLevel,omitempty"`
	SelectedClass      string                 `protobuf:"bytes,3,opt,name=selectedClass,proto3" json:"selectedClass,omitempty"`
	SelectedClassLevel float64                `protobuf:"fixed64,4,opt,name=selectedClassLevel,proto3" json:"selectedClassLevel,omitempty"`
	SecretsFound       float64                `protobuf:"fixed64,5,opt,name=secretsFound,proto3" json:"secretsFound,omitempty"`
	ClassLevel         *DungeonClasses        `protobuf:"bytes,6,opt,name=classLevel,proto3" json:"classLevel,omitempty"`
	M7                 *DungeonFloorStats     `protobuf:"bytes,7,opt,name=m7,proto3" json:"m7,omitempty"`
	Entrance           *DungeonFloorStats     `protobuf:"bytes,8,opt,name=entrance,proto3" json:"entrance,omitempty"`
	F1                 *DungeonFloorStats     `protobuf:"bytes,9,opt,name=f1,proto3" json:"f1,omitempty"`
	F2                 *DungeonFloorStats     `protobuf:"bytes,10,opt,name=f2,proto3" json:"f2,omitempty"`
	F3                 *DungeonFloorStats     `protobuf:"bytes,11,opt,name=f3,proto3" json:"f3,omitempty"`
	F4                 *DungeonFloorStats     `protobuf:"bytes,12,opt,name=f4,proto3" json:"f4,omitempty"`
	F5                 *DungeonFloorStats     `protobuf:"bytes,13,opt,name=f5,proto3" json:"f5,omitempty"`
	F6                 *DungeonFloorStats     `protobuf:"bytes,14,opt,name=f6,proto3" json:"f6,omitempty"`
	F7                 *DungeonFloorStats     `protobuf:"bytes,15,opt,name=f7,proto3" json:"f7,omitempty"`
	M1                 *DungeonFloorStats     `protobuf:"bytes,16,opt,name=m1,proto3" json:"m1,omitempty"`
	M2                 *DungeonFloorStats     `protobuf:"bytes,17,opt,name=m2,proto3" json:"m2,omitempty"`
	M3                 *DungeonFloorStats     `protobuf:"bytes,18,opt,name=m3,proto3" json:"m3,omitempty"`
	M4                 *DungeonFloorStats     `protobuf:"bytes,19,opt,name=m4,proto3" json:"m4,omitempty"`
	M5                 *DungeonFloorStats     `protobuf:"bytes,20,opt,name=m5,proto3" json:"m5,omitempty"`
	M6                 *DungeonFloorStats     `protobuf:"bytes,21,opt,name=m6,proto3" json:"m6,omitempty"`
	Profile            *SkyBlockProfile       `protobuf:"bytes,22,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DungeonsStatsResponse) Reset() {
	*x = DungeonsStatsResponse{}
	mi := &file_hypixel_hypixel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DungeonsStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DungeonsStatsResponse) ProtoMessage() {}

func (x *DungeonsStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hypixel_hypixel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DungeonsStatsResponse.ProtoReflect.Descriptor instead.
func (*DungeonsStatsResponse) Descriptor() ([]byte, []int) {
	return file_hypixel_hypixel_proto_rawDescGZIP(), []int{5}
}

func (x *DungeonsStatsResponse) GetClassAverage() float64 {
	if x != nil {
		return x.ClassAverage
	}
	return 0
}

func (x *DungeonsStatsResponse) GetCatacombsLevel() float64 {
	if x != nil {
		return x.CatacombsLevel
	}
	return 0
}

func (x *DungeonsStatsResponse) GetSelectedClass() string {
	if x != nil {
		return x.SelectedClass
	}
	return ""
}

func (x *DungeonsStatsResponse) GetSelectedClassLevel() float64 {
	if x != nil {
		return x.SelectedClassLevel
	}
	return 0
}

func (x *DungeonsStatsResponse) GetSecretsFound() float64 {
	if x != nil {
		return x.SecretsFound
	}
	return 0
}

func (x *DungeonsStatsResponse) GetClassLevel() *DungeonClasses {
	if x != nil {
		return x.ClassLevel
	}
	return nil
}

func (x *DungeonsStatsResponse) GetM7() *DungeonFloorStats {
	if x != nil {
		return x.M7
	}
	return nil
}

func (x *DungeonsStatsResponse) GetEntrance() *DungeonFloorStats {
	if x != nil {
		return x.Entrance
	}
	return nil
}

func (x *DungeonsStatsResponse) GetF1() *DungeonFloorStats {
	if x != nil {
		return x.F1
	}
	return nil
}

func (x *DungeonsStatsResponse) GetF2() *DungeonFloorStats {
	if x != nil {
		return x.F2
	}
	return nil
}

func (x *DungeonsStatsResponse) GetF3() *DungeonFloorStats {
	if x != nil {
		return x.F3
	}
	return nil
}

func (x *DungeonsStatsResponse) GetF4() *DungeonFloorStats {
	if x != nil {
		return x.F4
	}
	return nil
}

func (x *DungeonsStatsResponse) GetF5() *DungeonFloorStats {
	if x != nil {
		return x.F5
	}
	return nil
}

func (x *DungeonsStatsResponse) GetF6() *DungeonFloorStats {
	if x != nil {
		return x.F6
	}
	return nil
}

func (x *DungeonsStatsResponse) GetF7() *DungeonFloorStats {
	if x != nil {
		return x.F7
	}
	return nil
}

func (x *DungeonsStatsResponse) GetM1() *DungeonFloorStats {
	if x != nil {
		return x.M1
	}
	return nil
}

func (x *DungeonsStatsResponse) GetM2() *DungeonFloorStats {
	if x != nil {
		return x.M2
	}
	return nil
}

func (x *DungeonsStatsResponse) GetM3() *DungeonFloorStats {
	if x != nil {
		return x.M3
	}
	return nil
}

func (x *DungeonsStatsResponse) GetM4() *DungeonFloorStats {
	if x != nil {
		return x.M4
	}
	return nil
}

func (x *DungeonsStatsResponse) GetM5() *DungeonFloorStats {
	if x != nil {
		return x.M5
	}
	return nil
}

func (x *DungeonsStatsResponse) GetM6() *DungeonFloorStats {
	if x != nil {
		return x.M6
	}
	return nil
}

func (x *DungeonsStatsResponse) GetProfile() *SkyBlockProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

var File_hypixel_hypixel_proto protoreflect.FileDescriptor

const file_hypixel_hypixel_proto_rawDesc = "" +
	"\n" +
	"\x15hypixel/hypixel.proto\"G\n" +
	"\x0fSkyBlockRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x18\n" +
	"\aprofile\x18\x02 \x01(\tR\aprofile\"[\n" +
	"\x0fSkyBlockProfile\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x18\n" +
	"\aprofile\x18\x03 \x01(\tR\aprofile\"v\n" +
	"\x10NetworthResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x01R\x05total\x12 \n" +
	"\vunsoulbound\x18\x02 \x01(\x01R\vunsoulbound\x12*\n" +
	"\aprofile\x18\x03 \x01(\v2\x10.SkyBlockProfileR\aprofile\"\x82\x01\n" +
	"\x0eDungeonClasses\x12\x16\n" +
	"\x06healer\x18\x01 \x01(\x01R\x06healer\x12\x12\n" +
	"\x04mage\x18\x02 \x01(\x01R\x04mage\x12\x12\n" +
	"\x04tank\x18\x03 \x01(\x01R\x04tank\x12\x18\n" +
	"\aberserk\x18\x04 \x01(\x01R\aberserk\x12\x16\n" +
	"\x06archer\x18\x05 \x01(\x01R\x06archer\"Y\n" +
	"\x11DungeonFloorStats\x12 \n" +
	"\vcompletions\x18\x01 \x01(\x01R\vcompletions\x12\"\n" +
	"\fpersonalBest\x18\x02 \x01(\x01R\fpersonalBest\"\xe2\x06\n" +
	"\x15DungeonsStatsResponse\x12\"\n" +
	"\fclassAverage\x18\x01 \x01(\x01R\fclassAverage\x12&\n" +
	"\x0ecatacombsLevel\x18\x02 \x01(\x01R\x0ecatacombsLevel\x12$\n" +
	"\rselectedClass\x18\x03 \x01(\tR\rselectedClass\x12.\n" +
	"\x12selectedClassLevel\x18\x04 \x01(\x01R\x12selectedClassLevel\x12\"\n" +
	"\fsecretsFound\x18\x05 \x01(\x01R\fsecretsFound\x12/\n" +
	"\n" +
	"classLevel\x18\x06 \x01(\v2\x0f.DungeonClassesR\n" +
	"classLevel\x12\"\n" +
	"\x02m7\x18\a \x01(\v2\x12.DungeonFloorStatsR\x02m7\x12.\n" +
	"\bentrance\x18\b \x01(\v2\x12.DungeonFloorStatsR\bentrance\x12\"\n" +
	"\x02f1\x18\t \x01(\v2\x12.DungeonFloorStatsR\x02f1\x12\"\n" +
	"\x02f2\x18\n" +
	" \x01(\v2\x12.DungeonFloorStatsR\x02f2\x12\"\n" +
	"\x02f3\x18\v \x01(\v2\x12.DungeonFloorStatsR\x02f3\x12\"\n" +
	"\x02f4\x18\f \x01(\v2\x12.DungeonFloorStatsR\x02f4\x12\"\n" +
	"\x02f5\x18\r \x01(\v2\x12.DungeonFloorStatsR\x02f5\x12\"\n" +
	"\x02f6\x18\x0e \x01(\v2\x12.DungeonFloorStatsR\x02f6\x12\"\n" +
	"\x02f7\x18\x0f \x01(\v2\x12.DungeonFloorStatsR\x02f7\x12\"\n" +
	"\x02m1\x18\x10 \x01(\v2\x12.DungeonFloorStatsR\x02m1\x12\"\n" +
	"\x02m2\x18\x11 \x01(\v2\x12.DungeonFloorStatsR\x02m2\x12\"\n" +
	"\x02m3\x18\x12 \x01(\v2\x12.DungeonFloorStatsR\x02m3\x12\"\n" +
	"\x02m4\x18\x13 \x01(\v2\x12.DungeonFloorStatsR\x02m4\x12\"\n" +
	"\x02m5\x18\x14 \x01(\v2\x12.DungeonFloorStatsR\x02m5\x12\"\n" +
	"\x02m6\x18\x15 \x01(\v2\x12.DungeonFloorStatsR\x02m6\x12*\n" +
	"\aprofile\x18\x16 \x01(\v2\x10.SkyBlockProfileR\aprofile2{\n" +
	"\aHypixel\x122\n" +
	"\vGetNetworth\x12\x10.SkyBlockRequest\x1a\x11.NetworthResponse\x12<\n" +
	"\x10GetDungeonsStats\x12\x10.SkyBlockRequest\x1a\x16.DungeonsStatsResponseb\x06proto3"

var (
	file_hypixel_hypixel_proto_rawDescOnce sync.Once
	file_hypixel_hypixel_proto_rawDescData []byte
)

func file_hypixel_hypixel_proto_rawDescGZIP() []byte {
	file_hypixel_hypixel_proto_rawDescOnce.Do(func() {
		file_hypixel_hypixel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hypixel_hypixel_proto_rawDesc), len(file_hypixel_hypixel_proto_rawDesc)))
	})
	return file_hypixel_hypixel_proto_rawDescData
}

var file_hypixel_hypixel_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_hypixel_hypixel_proto_goTypes = []any{
	(*SkyBlockRequest)(nil),       // 0: SkyBlockRequest
	(*SkyBlockProfile)(nil),       // 1: SkyBlockProfile
	(*NetworthResponse)(nil),      // 2: NetworthResponse
	(*DungeonClasses)(nil),        // 3: DungeonClasses
	(*DungeonFloorStats)(nil),     // 4: DungeonFloorStats
	(*DungeonsStatsResponse)(nil), // 5: DungeonsStatsResponse
}
var file_hypixel_hypixel_proto_depIdxs = []int32{
	1,  // 0: NetworthResponse.profile:type_name -> SkyBlockProfile
	3,  // 1: DungeonsStatsResponse.classLevel:type_name -> DungeonClasses
	4,  // 2: DungeonsStatsResponse.m7:type_name -> DungeonFloorStats
	4,  // 3: DungeonsStatsResponse.entrance:type_name -> DungeonFloorStats
	4,  // 4: DungeonsStatsResponse.f1:type_name -> DungeonFloorStats
	4,  // 5: DungeonsStatsResponse.f2:type_name -> DungeonFloorStats
	4,  // 6: DungeonsStatsResponse.f3:type_name -> DungeonFloorStats
	4,  // 7: DungeonsStatsResponse.f4:type_name -> DungeonFloorStats
	4,  // 8: DungeonsStatsResponse.f5:type_name -> DungeonFloorStats
	4,  // 9: DungeonsStatsResponse.f6:type_name -> DungeonFloorStats
	4,  // 10: DungeonsStatsResponse.f7:type_name -> DungeonFloorStats
	4,  // 11: DungeonsStatsResponse.m1:type_name -> DungeonFloorStats
	4,  // 12: DungeonsStatsResponse.m2:type_name -> DungeonFloorStats
	4,  // 13: DungeonsStatsResponse.m3:type_name -> DungeonFloorStats
	4,  // 14: DungeonsStatsResponse.m4:type_name -> DungeonFloorStats
	4,  // 15: DungeonsStatsResponse.m5:type_name -> DungeonFloorStats
	4,  // 16: DungeonsStatsResponse.m6:type_name -> DungeonFloorStats
	1,  // 17: DungeonsStatsResponse.profile:type_name -> SkyBlockProfile
	0,  // 18: Hypixel.GetNetworth:input_type -> SkyBlockRequest
	0,  // 19: Hypixel.GetDungeonsStats:input_type -> SkyBlockRequest
	2,  // 20: Hypixel.GetNetworth:output_type -> NetworthResponse
	5,  // 21: Hypixel.GetDungeonsStats:output_type -> DungeonsStatsResponse
	20, // [20:22] is the sub-list for method output_type
	18, // [18:20] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_hypixel_hypixel_proto_init() }
func file_hypixel_hypixel_proto_init() {
	if File_hypixel_hypixel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hypixel_hypixel_proto_rawDesc), len(file_hypixel_hypixel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hypixel_hypixel_proto_goTypes,
		DependencyIndexes: file_hypixel_hypixel_proto_depIdxs,
		MessageInfos:      file_hypixel_hypixel_proto_msgTypes,
	}.Build()
	File_hypixel_hypixel_proto = out.File
	file_hypixel_hypixel_proto_goTypes = nil
	file_hypixel_hypixel_proto_depIdxs = nil
}
